export const metadata = {
    title: "About",
    description: 'Generated by create next app',
}

export default function About() {
    return (
      <div className="">
        <h2>About Page</h2>
      </div>
    )
  }